env:
  browser: false
  node: true
extends: airbnb
parser: babel-eslint
installedESLint: true
globals:
  log: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  no-console:
    - warn
  new-cap:
    - off
  no-underscore-dangle:
    - off
  # import/no-extraneous-dependencies:
  #   - off
  # import/extensions:
  #   - off
  # import/no-unresolved:
  #   - off
